export const INSPIRATION_QUOTES = [
  { text: "Gratitude turns what we have into enough.", author: "Aesop" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "When I started counting my blessings, my whole life turned around.", author: "Willie Nelson" },
  { text: "Wear gratitude like a cloak, and it will feed every corner of your life.", author: "Rumi" },
  { text: "The root of joy is gratefulness.", author: "David Steindl-Rast" },
  { text: "Gratitude is not only the greatest of virtues, but the parent of all the others.", author: "Cicero" },
  { text: "Acknowledging the good that you already have in your life is the foundation for all abundance.", author: "Eckhart Tolle" },
  { text: "It is not happiness that brings us gratitude. It is gratitude that brings us happiness.", author: "Unknown" },
  { text: "Enjoy the little things, for one day you may look back and realize they were the big things.", author: "Robert Brault" },
  { text: "The heart that gives thanks is a happy one.", author: "Douglas Wood" },
  { text: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", author: "Melody Beattie" },
  { text: "Give yourself a gift of five minutes of contemplation in awe of everything you see around you.", author: "Wayne Dyer" },
  { text: "The real gift of gratitude is that the more grateful you are, the more present you become.", author: "Robert Holden" },
  { text: "Silent gratitude isn't much use to anyone.", author: "Gladys Bronwyn Stern" },
  { text: "A grateful heart is a magnet for miracles.", author: "Unknown" },
  { text: "Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom.", author: "Marcel Proust" },
  { text: "Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously.", author: "Ralph Waldo Emerson" },
  { text: "Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author: "William Arthur Ward" },
  { text: "When we focus on our gratitude, the tide of disappointment goes out and the tide of love rushes in.", author: "Kristin Armstrong" },
  { text: "Gratitude is the sign of noble souls.", author: "Aesop" },
  { text: "Gratitude unlocks the fullness of life. It turns what we have into enough, and more.", author: "Melody Beattie" },
  { text: "We must find time to stop and thank the people who make a difference in our lives.", author: "John F. Kennedy" },
  { text: "Be thankful for what you have; you'll end up having more.", author: "Oprah Winfrey" },
  { text: "Thankfulness is the beginning of gratitude. Gratitude is the completion of thankfulness.", author: "Henri Frédéric Amiel" },
  { text: "Gratitude is when memory is stored in the heart and not in the mind.", author: "Lionel Hampton" },
  { text: "If the only prayer you ever said was thank you, that would be enough.", author: "Meister Eckhart" },
  { text: "Some people grumble that roses have thorns; I am grateful that thorns have roses.", author: "Alphonse Karr" },
  { text: "Praise the bridge that carried you over.", author: "George Colman" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus" },
  { text: "Reflect upon your present blessings, of which every man has many; not on your past misfortunes, of which all men have some.", author: "Charles Dickens" },
  { text: "Gratitude can transform common days into thanksgivings, turn routine jobs into joy, and change ordinary opportunities into blessings.", author: "William Arthur Ward" },
  { text: "When eating bamboo sprouts, remember the man who planted them.", author: "Chinese proverb" },
  { text: "The essence of all beautiful art, all great art, is gratitude.", author: "Friedrich Nietzsche" },
  { text: "Gratitude is the healthiest of all human emotions.", author: "Zig Ziglar" },
  { text: "Appreciation is a wonderful thing. It makes what is excellent in others belong to us as well.", author: "Voltaire" },
  { text: "Gratitude is the fairest blossom which springs from the soul.", author: "Henry Ward Beecher" },
  { text: "I would maintain that thanks are the highest form of thought, and that gratitude is happiness doubled by wonder.", author: "G.K. Chesterton" },
  { text: "In ordinary life we hardly realize that we receive a great deal more than we give, and that it is only with gratitude that life becomes rich.", author: "Dietrich Bonhoeffer" },
  { text: "Gratitude is the open door to abundance.", author: "Yogi Bhajan" },
  { text: "Gratitude is a currency that we can mint for ourselves, and spend without fear of bankruptcy.", author: "Fred De Witt Van Amburgh" },
  { text: "Gratitude is the memory of the heart.", author: "Jean Baptiste Massieu" },
  { text: "When you are grateful, fear disappears and abundance appears.", author: "Anthony Robbins" },
  { text: "Walk as if you are kissing the earth with your feet.", author: "Thich Nhat Hanh" },
  { text: "Smile, breathe, and go slowly.", author: "Thich Nhat Hanh" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
  { text: "Peace is every step.", author: "Thich Nhat Hanh" },
  { text: "Hope is important because it can make the present moment less difficult to bear.", author: "Thich Nhat Hanh" },
  { text: "Because of your smile, you make life more beautiful.", author: "Thich Nhat Hanh" },
  { text: "Every breath we take, every step we make, can be filled with peace, joy, and serenity.", author: "Thich Nhat Hanh" },
  { text: "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "Let us rise up and be thankful, for if we didn't learn a lot today, at least we learned a little.", author: "Buddha" },
  { text: "The way to happiness: keep your heart free from hate, your mind from worry. Live simply, expect little, give much.", author: "Norman Vincent Peale" },
  { text: "Joy is the simplest form of gratitude.", author: "Karl Barth" },
  { text: "Keep your face always toward the sunshine — and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "Give thanks for a little and you will find a lot.", author: "Hausa proverb" },
  { text: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon" },
  { text: "Nothing is more honorable than a grateful heart.", author: "Seneca" },
  { text: "No one who achieves success does so without acknowledging the help of others.", author: "Alfred North Whitehead" },
  { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { text: "Happiness is the spiritual experience of living every minute with love, grace, and gratitude.", author: "Denis Waitley" },
  { text: "The more grateful I am, the more beauty I see.", author: "Mary Davis" },
  { text: "Gratitude bestows reverence, allowing us to encounter everyday epiphanies.", author: "John Milton" },
  { text: "If you concentrate on finding whatever is good in every situation, you will discover that your life will suddenly be filled with gratitude.", author: "Harold Kushner" },
  { text: "Gratitude is an antidote to negative emotions, a neutralizer of envy, hostility, worry, and irritation.", author: "Sonja Lyubomirsky" },
  { text: "When we give cheerfully and accept gratefully, everyone is blessed.", author: "Maya Angelou" },
  { text: "This is a wonderful day. I've never seen this one before.", author: "Maya Angelou" },
  { text: "Be a rainbow in someone else's cloud.", author: "Maya Angelou" },
  { text: "I've learned that people will forget what you said, but they will never forget how you made them feel.", author: "Maya Angelou" },
  { text: "You cannot do a kindness too soon, for you never know how soon it will be too late.", author: "Ralph Waldo Emerson" },
  { text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { text: "Nothing is worth more than this day.", author: "Johann Wolfgang von Goethe" },
  { text: "There is a calmness to a life lived in gratitude, a quiet joy.", author: "Ralph H. Blum" },
  { text: "Gratitude is one of the sweet shortcuts to finding peace of mind and happiness inside.", author: "Barry Neil Kaufman" },
  { text: "If you want to find happiness, find gratitude.", author: "Steve Maraboli" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "At times our own light goes out and is rekindled by a spark from another person.", author: "Albert Schweitzer" },
  { text: "No duty is more urgent than that of returning thanks.", author: "James Allen" },
  { text: "He who thanks but with the lips thanks but in part.", author: "Henry Melville" },
  { text: "I awoke this morning with devout thanksgiving for my friends, the old and the new.", author: "Ralph Waldo Emerson" },
  { text: "Life without thankfulness is devoid of love and passion.", author: "Elder Paisios" },
  { text: "Gratitude makes us like children again.", author: "John Vianney" },
  { text: "Every moment of our life can be the beginning of great things.", author: "Henri-Frédéric Amiel" },
  { text: "Always have an attitude of gratitude.", author: "Sterling K. Brown" },
  { text: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", author: "Albert Einstein" },
  { text: "Gratitude, like faith, is a muscle. The more you use it, the stronger it grows.", author: "Alan Cohen" },
  { text: "Gratefulness is the key to a happy life that we hold in our hands.", author: "David Steindl-Rast" },
  { text: "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.", author: "Lao Tzu" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Being deeply loved gives you strength; loving someone deeply gives you courage.", author: "Lao Tzu" },
  { text: "Contentment makes poor men rich; discontent makes rich men poor.", author: "Benjamin Franklin" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { text: "In the end, it's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "The secret of happiness is not found in seeking more, but in developing the capacity to enjoy less.", author: "Socrates" },
  { text: "The only thing that makes a place a paradise is the people we share it with.", author: "Elbert Hubbard" },
  { text: "In everything give thanks.", author: "1 Thessalonians 5:18" },
  { text: "Give thanks to the Lord, for he is good; his love endures forever.", author: "Psalm 107:1" },
  { text: "Enter his gates with thanksgiving and his courts with praise.", author: "Psalm 100:4" },
  { text: "Be thankful for this moment. This moment is your life.", author: "Omar Khayyám" },
  { text: "If you look at what you have, you'll always have more. If you look at what you don't, you'll never have enough.", author: "Oprah Winfrey" },
  { text: "The struggle ends when the gratitude begins.", author: "Neale Donald Walsch" },
  { text: "Rest and be thankful.", author: "William Wordsworth" },
  { text: "The way to develop the best that is in a person is by appreciation and encouragement.", author: "Charles Schwab" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "The present moment is the only moment available to us, and it is the door to all moments.", author: "Thich Nhat Hanh" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "Be grateful for whoever comes, because each has been sent as a guide from beyond.", author: "Rumi" },
  { text: "What you seek is seeking you.", author: "Rumi" },
  { text: "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", author: "Rumi" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi" },
  { text: "Do not grieve. Anything you lose comes round in another form.", author: "Rumi" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", author: "Rumi" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "All that we are is the result of what we have thought.", author: "Buddha" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius" },
  { text: "The best revenge is not to be like your enemy.", author: "Marcus Aurelius" },
  { text: "Our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look there.", author: "Marcus Aurelius" },
  { text: "Every man's life lies within the present; for the past is spent, and the future is uncertain.", author: "Marcus Aurelius" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "Any person capable of angering you becomes your master.", author: "Epictetus" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca" },
  { text: "A gift consists not in what is done or given, but in the intention of the giver or doer.", author: "Seneca" },
  { text: "Wealth is the ability to fully experience life.", author: "Henry David Thoreau" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { text: "Happiness is like a butterfly; the more you chase it, the more it will elude you.", author: "Henry David Thoreau" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Finish each day and be done with it. You have done what you could.", author: "Ralph Waldo Emerson" },
  { text: "Life is a journey, not a destination.", author: "Ralph Waldo Emerson" },
  { text: "Write it on your heart that every day is the best day in the year.", author: "Ralph Waldo Emerson" },
  { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "When you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
  { text: "Be grateful for what you already have while you pursue your goals.", author: "Roy T. Bennett" },
  { text: "Happiness itself is a kind of gratitude.", author: "Joseph Wood Krutch" },
  { text: "Piglet noticed that even though he had a very small heart, it could hold a rather large amount of gratitude.", author: "A.A. Milne" },
  { text: "Once you take note of the things you are grateful for, you begin to lose sight of the things that you lack.", author: "Germany Kent" },
  { text: "Forever on Thanksgiving, the heart will find the pathway home.", author: "Wilbur D. Nesbit" },
  { text: "Gratitude is the sweetest thing in a seeker's life.", author: "Sri Chinmoy" },
  { text: "Gratitude is the inward feeling of kindness received. Thankfulness is the natural impulse to express it.", author: "Henry Van Dyke" },
  { text: "Gratitude is a powerful catalyst for happiness.", author: "Amy Collette" },
  { text: "Gratitude is a quality similar to electricity: it must be produced and discharged in order to exist at all.", author: "William Faulkner" },
  { text: "Gratitude is the best attitude.", author: "Unknown" },
  { text: "Wake up every morning with the thought that something wonderful is about to happen.", author: "Unknown" },
  { text: "Joy is what happens to us when we allow ourselves to recognize how good things really are.", author: "Marianne Williamson" },
  { text: "In daily life, it is not happiness that makes us grateful, but gratefulness that makes us happy.", author: "Albert Clarke" },
  { text: "Happiness is the consequence of personal effort. You fight for it, strive for it, insist upon it.", author: "Elizabeth Gilbert" },
  { text: "A beautiful day begins with a beautiful mindset.", author: "Unknown" },
  { text: "The soul that gives thanks can find comfort in everything.", author: "Hannah Whitall Smith" },
  { text: "The more you practice the art of thankfulness, the more you have to be thankful for.", author: "Norman Vincent Peale" },
  { text: "Trade your expectations for appreciation and the world changes instantly.", author: "Tony Robbins" },
  { text: "Gratitude is the wine for the soul. Go on. Get drunk.", author: "Rumi" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
  { text: "I hear and I forget. I see and I remember. I do and I understand.", author: "Confucius" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { text: "Silence is a true friend who never betrays.", author: "Confucius" },
  { text: "Study the past if you would define the future.", author: "Confucius" },
  { text: "Life is 10% what happens to me and 90% of how I react to it.", author: "Charles R. Swindoll" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "We make a living by what we get. We make a life by what we give.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { text: "Never, never, never give up.", author: "Winston Churchill" },
  { text: "Kites rise highest against the wind, not with it.", author: "Winston Churchill" },
  { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author: "Winston Churchill" },
  { text: "Joy is prayer. Joy is strength. Joy is love. Joy is a net of love by which you can catch souls.", author: "Mother Teresa" },
  { text: "Let no one ever come to you without leaving better and happier.", author: "Mother Teresa" },
  { text: "Do small things with great love.", author: "Mother Teresa" },
  { text: "We ourselves feel that what we are doing is just a drop in the ocean. But the ocean would be less because of that missing drop.", author: "Mother Teresa" },
  { text: "Peace begins with a smile.", author: "Mother Teresa" },
  { text: "Intense love does not measure, it just gives.", author: "Mother Teresa" },
  { text: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa" },
  { text: "Gratitude is riches. Complaint is poverty.", author: "Doris Day" },
  { text: "When you are grateful, you find the bright spot in every cloud.", author: "Unknown" },
  { text: "Wake at dawn with a winged heart and give thanks for another day of loving.", author: "Kahlil Gibran" },
  { text: "The earth delights to feel your bare feet and the winds long to play with your hair.", author: "Kahlil Gibran" },
  { text: "Yesterday is history, tomorrow is a mystery, today is a gift — which is why we call it the present.", author: "Bil Keane" },
  { text: "Today is a new day. Don't let your history interfere with your destiny.", author: "Steve Maraboli" },
  { text: "The power of finding beauty in the humblest things makes home happy and life lovely.", author: "Louisa May Alcott" },
  { text: "It's not what you look at that matters, it's what you see.", author: "Henry David Thoreau" },
  { text: "Happiness cannot be found through great effort and willpower, but is already present, in open relaxation and letting go.", author: "Ram Dass" },
  { text: "The most important thing in life is to learn how to give out love, and to let it come in.", author: "Morrie Schwartz" },
  { text: "The quieter you become, the more you can hear.", author: "Ram Dass" },
  { text: "We're all just walking each other home.", author: "Ram Dass" },
  { text: "Be here now.", author: "Ram Dass" },
  { text: "The next message you need is always right where you are.", author: "Ram Dass" },
  { text: "Treat everyone you meet like God in drag.", author: "Ram Dass" },
  { text: "Gratitude is the state of thankful appreciation for what one receives.", author: "Robert Emmons" },
  { text: "I don't have to chase extraordinary moments to find happiness. It's right in front of me if I'm paying attention.", author: "Brené Brown" },
  { text: "Vulnerability sounds like truth and feels like courage.", author: "Brené Brown" },
  { text: "Courage starts with showing up and letting ourselves be seen.", author: "Brené Brown" },
  { text: "Talk to yourself like you would to someone you love.", author: "Brené Brown" },
  { text: "Sometimes the bravest and most important thing you can do is just show up.", author: "Brené Brown" },
  { text: "Owning our story and loving ourselves through that process is the bravest thing we will ever do.", author: "Brené Brown" },
  { text: "Compassion is not a relationship between the healer and the wounded. It's a relationship between equals.", author: "Pema Chödrön" },
  { text: "Nothing ever goes away until it has taught us what we need to know.", author: "Pema Chödrön" },
  { text: "Start where you are. This is very important.", author: "Pema Chödrön" },
  { text: "You are the sky. Everything else — it's just the weather.", author: "Pema Chödrön" },
  { text: "Meditation isn't about trying to throw ourselves away; it's about befriending who we are already.", author: "Pema Chödrön" },
  { text: "Be kinder to yourself. And then let your kindness flood the world.", author: "Pema Chödrön" },
  { text: "The way to dissolve our resistance to life is to meet it face to face.", author: "Pema Chödrön" },
  { text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { text: "In the midst of movement and chaos, keep stillness inside of you.", author: "Deepak Chopra" },
  { text: "The best use of imagination is creativity. The worst use of imagination is anxiety.", author: "Deepak Chopra" },
  { text: "In the process of letting go you will lose many things from the past, but you will find yourself.", author: "Deepak Chopra" },
  { text: "Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.", author: "Deepak Chopra" },
  { text: "Gratitude opens the door to the power, the wisdom, the creativity of the universe.", author: "Deepak Chopra" },
  { text: "Comfort in expressing your emotions allows you to share the best of yourself with others.", author: "Iyanla Vanzant" },
  { text: "Today is the day to be grateful for your life.", author: "Unknown" },
  { text: "You must learn to let go. Release the stress. You were never in control anyway.", author: "Steve Maraboli" },
  { text: "Give thanks not just on Thanksgiving Day, but every day of your life.", author: "Catherine Pulsifer" },
  { text: "Stop now. Enjoy the moment. It's now or never.", author: "Maxime Lagacé" },
  { text: "Gratitude is the humble courage to meet what is, with all one has.", author: "Unknown" },
  { text: "When gratitude becomes essential, miracles start to appear everywhere.", author: "Emmanuel Dagher" },
  { text: "Gratitude is a feeling that lifts us up and motivates us to create positive change.", author: "Unknown" },
  { text: "The more gratitude I feel, the more I find to be grateful for.", author: "Unknown" },
  { text: "Each day offers the gift of being a special occasion if we can learn to receive with grace.", author: "Sarah Ban Breathnach" },
  { text: "If you're not grateful for what you've already got, what makes you think you'd be happy with more?", author: "Zig Ziglar" },
  { text: "An attitude of gratitude brings great things.", author: "Yogi Bhajan" },
  { text: "Giving thanks for abundance is sweeter than the abundance itself.", author: "Rumi" },
  { text: "A single grateful thought toward heaven is the most complete prayer.", author: "Gotthold Ephraim Lessing" },
  { text: "Now is no time to think of what you do not have. Think of what you can do with what there is.", author: "Ernest Hemingway" },
  { text: "The thankful receiver bears a plentiful harvest.", author: "William Blake" },
  { text: "Gratitude is an art of painting adversity into a lovely picture.", author: "Kak Sri" },
  { text: "Gratitude is a vaccine, an antitoxin, and an antiseptic.", author: "John Henry Jowett" },
  { text: "A sense of gratitude for what you have right here, right now is one of the greatest gifts we can give ourselves.", author: "Oprah Winfrey" },
  { text: "Gratitude lies in our attitude.", author: "Unknown" },
  { text: "As each day comes refreshed and anew, so does my gratitude renew itself daily.", author: "Terri Guillemets" },
  { text: "Your own positive future begins in this moment. All you have is right now.", author: "Lao Tzu" },
  { text: "A single act of kindness throws out roots in all directions.", author: "Amelia Earhart" },
  { text: "Keep your thoughts positive because your thoughts become your words.", author: "Mahatma Gandhi" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { text: "Gentleness, self-sacrifice, and generosity are the exclusive possession of no one race or religion.", author: "Mahatma Gandhi" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
  { text: "We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses.", author: "Abraham Lincoln" },
  { text: "The most beautiful thing we can experience is the mysterious.", author: "Albert Einstein" },
  { text: "There is nothing in a caterpillar that tells you it's going to be a butterfly.", author: "R. Buckminster Fuller" },
  { text: "Even in a time of greed, one never has to look far to see the campfires of gentle people.", author: "Garrison Keillor" },
  { text: "Gratitude is a fountain that, when drunk from, replenishes itself.", author: "Unknown" },
  { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "The greatest gift you can give someone is your time.", author: "Rick Warren" },
  { text: "Let gratitude be the pillow upon which you kneel to say your nightly prayer.", author: "Maya Angelou" },
  { text: "Gratitude is the ability to experience life as a gift.", author: "John Ortberg" },
  { text: "There is always, always, always something to be thankful for.", author: "Unknown" },
  { text: "The simple act of saying thank you is a demonstration of gratitude.", author: "Alice Walker" },
  { text: "Life becomes easier when you learn to accept an apology you never got.", author: "Robert Brault" },
  { text: "Develop an attitude of gratitude, and give thanks for everything that happens to you.", author: "Brian Tracy" },
  { text: "Wear gratitude like a cloak.", author: "Rumi" },
  { text: "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice.", author: "Brian Herbert" },
  { text: "Friends are the family you choose.", author: "Jess C. Scott" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "You must have chaos within you to give birth to a dancing star.", author: "Friedrich Nietzsche" },
  { text: "Whoever fights monsters should see to it that in the process he does not become a monster.", author: "Friedrich Nietzsche" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "Every morning brings new potential, but only if you make the most of it.", author: "Paulo Coelho" },
  { text: "Whenever you want to achieve something, keep your eyes open, concentrate and make sure you know exactly what it is you want.", author: "Paulo Coelho" },
  { text: "When we least expect it, life sets us a challenge to test our courage and willingness to change.", author: "Paulo Coelho" },
  { text: "Tears are words that need to be written.", author: "Paulo Coelho" },
  { text: "And, when you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho" },
  { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { text: "Some of the best moments of our lives are the ones we didn't plan.", author: "Unknown" },
  { text: "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.", author: "Vivian Greene" },
  { text: "Life is a great big canvas, and you should throw all the paint on it you can.", author: "Danny Kaye" },
  { text: "There are no strangers here; only friends you haven't yet met.", author: "W.B. Yeats" },
  { text: "All that is gold does not glitter, not all those who wander are lost.", author: "J.R.R. Tolkien" },
  { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
  { text: "A thankful heart is not only the greatest virtue, but the parent of all other virtues.", author: "Cicero" },
  { text: "When we replay our experiences we savor them; when we savor them we multiply them.", author: "Unknown" },
  { text: "Life is short. Be swift to love! Make haste to be kind!", author: "Henri-Frédéric Amiel" },
  { text: "Thank you is the best prayer that anyone could say. It expresses extreme gratitude, humility, and understanding.", author: "Alice Walker" },
];
