INSERT INTO questions (text, category) VALUES
('What is a skill or talent you are grateful for?', 'self'),
('What is a recent challenge you overcame?', 'self'),
('What is a favorite memory you are thankful for?', 'reflection'),
('What is something in nature you noticed today?', 'environment'),
('What is a comforting object or possession you cherish?', 'environment'),
('Who made you laugh recently?', 'relationships'),
('What is a recent act of kindness you experienced?', 'relationships'),
('What is a food or drink that brought you pleasure today?', 'sensory'),
('What is a song, smell, or image that lifted your mood?', 'sensory'),
('What is something about your morning routine you enjoy?', 'daily'),
('What is something you learned recently that you are grateful for?', 'self'),
('What is a moment of quiet or peace you appreciated?', 'daily'),
('What is a way technology made your life easier today?', 'reflection'),
('Who is a mentor or guide that impacted you?', 'relationships'),
('What is a cozy or safe place you are thankful for?', 'environment'),
('What is a moment today that made you feel alive?', 'daily'),
('What is a book, movie, or show that enriched your life?', 'self'),
('What is a habit that improves your wellbeing?', 'health'),
('What is a goal you achieved recently, big or small?', 'future'),
('What is an upcoming event or plan you are excited about?', 'future');
('What is something small that made you smile today?', 'daily'),
('Who is someone you appreciate and why?', 'relationships'),
('What is something your body allowed you to do today?', 'health'),
('What is a place that brings you comfort?', 'environment'),
('What is something you often take for granted?', 'reflection'),
('What is something that went right today?', 'daily'),
('Who helped you recently, even in a small way?', 'relationships'),
('What is a sound, smell, or sight you enjoyed today?', 'sensory'),
('What is something you are proud of yourself for?', 'self'),
('What is something you are looking forward to?', 'future');
